name: CI frontend

on:
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Debug Modified Files
      run: echo "Modified files lll ${{ github.event.head_commit.modified }}"

  build:
    runs-on: ubuntu-latest
    
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      (
        contains(github.event.head_commit.modified, 'package.json') ||
        contains(github.event.head_commit.modified, 'Dockerfile') ||
        startsWith(github.event.head_commit.modified, 'src/')
      )
      
    needs: debug  # Ajoutez cette ligne pour s'assurer que le job debug s'exécute en premier
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular app
      run: |
        npm run build

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Setup
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_ci:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend_ci:latest
