name: CI frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Debug Current Directory
        run: |
          echo "Current Directory: $(pwd)"

      - name: Build Angular app
        run: |
          npm run build
          ls -l dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: Docker Setup
        run: |
          pwd
          ls
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_ci:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_ci:latest
