name: CI frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Debug Current Directory
        run: |
          echo "Current Directory: $(pwd)"

      - name: Build Angular app
        run: |
          npm run build
          ls -l dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      
      - name: set variable
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo $GITHUB_SHA_SHORT
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/frontend_ci:V${GITHUB_SHA_SHORT}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      
      - name: Docker Setup
        run: |
          image_tag="${IMAGE_TAG}"
          docker build -t $image_tag .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push $image_tag

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update image version in YAML
        run: |
          commit_sha=$COMMIT_SHA
          sed -i 's|image: dahhouilyas/frontend_ci:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend_ci:${commit_sha}|' dev/frontend.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dev/frontend.yaml
          git commit -m "Update image version in Kubernetes YAML [skip ci]"
          git push