name: CI frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.4  # Spécifiez une version qui prend en charge Node.js 16.

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular app
      run: |
        npm run build

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.4  # Spécifiez la même version que dans la première étape.

    - name: Docker Setup
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-ci:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-ci:latest
